# prowlarr.yml
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - suaPasta/config/prowlarr:/config
    ports:
      - 9696:9696
    dns:
      - 1.1.1.1
      - 8.8.8.8
    restart: unless-stopped
