# radarr.yml
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - suaPasta/config/radarr:/config
      - suaPasta/media:/media:z
      - suaPasta/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
