# sonarr.yml
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - suaPasta/config/sonarr:/config
      - suaPasta/media:/media
      - suaPasta/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
